# Generated by Django 3.1.7 on 2021-04-11 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('season', models.PositiveIntegerField()),
                ('score', models.IntegerField()),
                ('production_studio', models.CharField(max_length=200)),
                ('number_of_episodes', models.PositiveIntegerField()),
                ('episode_duration', models.PositiveIntegerField()),
                ('synopsis', models.TextField()),
                ('rating', models.IntegerField()),
                ('URL', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Anime',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('photo_de_profil', models.CharField(max_length=200)),
                ('sexe', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('animes', models.ManyToManyField(to='recommandation.Anime')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('score', models.IntegerField()),
                ('description', models.TextField()),
                ('id_anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommandation.anime')),
                ('id_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommandation.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, default=None, null=True)),
                ('id_anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommandation.anime')),
                ('id_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommandation.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Preferer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommandation.genre')),
                ('id_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommandation.utilisateur')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(to='recommandation.Genre'),
        ),
    ]
