# Generated by Django 3.1.7 on 2021-03-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('season', models.PositiveIntegerField()),
                ('score', models.IntegerField()),
                ('production_studio', models.CharField(max_length=200)),
                ('number_of_episodes', models.PositiveIntegerField()),
                ('episode_duration', models.PositiveIntegerField()),
                ('synopsis', models.TextField()),
                ('rating', models.IntegerField()),
                ('URL', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wording', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=200)),
                ('bio', models.TextField(default='')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200, unique=True)),
                ('profile_picture', models.URLField(default='')),
                ('sexe', models.CharField(default='', max_length=200)),
                ('age', models.PositiveIntegerField(default='')),
            ],
        ),
    ]
