# Generated by Django 3.1.7 on 2021-03-24 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommandation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterModelOptions(
            name='anime',
            options={'verbose_name_plural': 'Anime'},
        ),
    ]
