# Generated by Django 3.1.7 on 2021-04-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommandation', '0003_auto_20210412_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
