# Generated by Django 3.1.7 on 2021-04-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommandation', '0004_auto_20210412_1835'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='genres',
            field=models.ManyToManyField(to='recommandation.Genre'),
        ),
    ]
