# Generated by Django 3.1.7 on 2021-04-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommandation', '0005_auto_20210415_1239'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='animes',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='genres',
        ),
        migrations.AlterField(
            model_name='recommandation',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
