# Generated by Django 3.1.7 on 2021-04-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommandation', '0006_auto_20210421_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommandation',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True),
        ),
    ]
