# Generated by Django 3.1.7 on 2021-05-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommandation', '0007_auto_20210421_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='sexe',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
